import './contenido.css';
import Count from './Contador.jsx'
function Contenido(){
    return(
        <div className='contendor-contenido'>
            <div>
                <h1>Pokemon</h1>
                <p><b>Pokémon</b> es una franquicia de videojuegos que comenzó siendo tipo RPG para las consolas de Nintendo creada por Satoshi Tajiri en 1995. Su éxito fue tal que abarcó otros géneros de videojuegos y campos del entretenimiento tales como una serie de anime, manga y una gran variedad de artículos de colección, como cartas del JCC Pokémon, muñecos, etc.</p>
                <p>Antes de la llegada de Pokémon Rojo y Azul a España, se publicó una revista llamada Los libros de Neko: Pocket Monster's, que avanzaba detalles sobre la franquicia. Actualmente Pokémon en España dispone de una revista llamada Pokémon: La revista oficial para todos los lectores, distribuida y publicada por Panini Revistas.</p>
                <h2 id="Etimologia">1 Etimología</h2>
                <p>La palabra <b>Pokémon</b> es la escritura con letras latinas de las japonesas: "ポケモン", que son una abreviatura de <b>Poke</b>tto <b>Mon</b>sutta, que a su vez proviene del inglés <b>'Pocket Monters'</b>, que quiere "Monstruo de Bolsillo". Esto viene del hecho que los Pokémon se guardan en <b>Pokeballs</b>, las cuales se pueden encoger con lo que se pueden meter en el bolsillo. Además, originalmente, Pokémon fue lanzado para Game Boy, consola que cabe perfectamente en un bolsillo, que casualmenmte de preferencia al nombre de la serie, videojuego, juego de mesa, etc.</p>
                <p>En inglés, la palabra se escribe Pokémon con tilde en acento agudo, a pesar de que este signo no existe en el uso habitual de este idioma. Esto se debe a que al uniser las palabras Pocket Monster se obtuvo Pokemon. El problema es que según las normas de inglés, esto se pronuncia como (pouk mon). En muy pocos otros casos se puede poner en inglés un acento en la "e" para que se pronuncie, resultando así el nombre "Pokémon". En español se puede usar la transcripción romaji que prescinde del acento por razones ortográficas, si bien en el uso comercial habitualmente aparece usando la tilde.</p>
                <h2 id="Historia">2 Historia</h2>
                <p>La historia de la franquicia Pokémon se expande más allá de una década desde que comenzó a trabajar oficialmente en el primer juego hasta ahora y tiene raíces incluso antiguas. Empezó como el hobby de Satoshi Tajiri, quien desde niño disfrutaba cazando insectos y renacuajos en un bosque cerca de su casa, en el suburbano de Tokio. Pasado un tiempo ese bosque que visitaba fue destruido, y en base a aquel suceso Satoshi decidió poner en práctica su afición de capturar insectos porque quería que los niños disfrutasen tanto como él lo había hecho hasta aquel día. Gracias a la ayuda de Shigeru Miyamoto consiguió que Nintendo valorara su proyecto que finalmente se comercializó el 27 de Febrero de 1996. Después de ese día y debido al enorme éxito Nintendo continuó desarrollando juegos Pokémon para la mayoría de sus plataformas.</p>
                <h2 id="Pokemon">3 ¿Qué son los Pokemones?</h2>
                <p>Los Pokemones son criaturas ficticias, que dependiendo de la especie o el tipo, pueden tener rasgos físicos parecidos a animales, plantas, rocas, fantasmas, o incluso humanos (aunque de tamaño en muchos casos muy superiores a lo que mediría la especie a la que se parece). Poseen poderes fantásticos que pueden utilizar llevando a cabo movimientos o habilidades para atacar, defenderse o cumplir sus necesidades. Generalmente pueden vivir en todo tipo de entornos, subsistiendo de la naturaleza o conviviendo con humanos y ayudándolos.</p>
                <h3 id="Vinculo">3.1 Vínculo entre Humanos y Pokémon</h3>
                <p>Los Pokemones pueden desarrollar vínculos muy especiales con sus dueños, quienes pueden decidir que hacer con ellos. Algunos tienen a los Pokémon como mascotas, para protegerse de otros Pokémones Salvajes, para ayudarles en sus tareas domésticas o incluso para llevar a cabo trabajos, y también hay quienes los utilizan para luchar contra otros Pokémon de otras personas en combates Pokémon y medir su potencial (se les conoce como entrenadores Pokémon) o participar en Concursos Pokémon y lucir sus cualiddades (conocidos como Coordinadores Pokémon).</p>
                <p>Los humanos pueden capturar Pokémon con las Pokéballs, que poseen una misteriosa energía que permite introducir a un Pokémon dentro de un espacio muy reducido y permitir transportarlos cómodamente. De ahí lo de Monstruos de Bolsillo. Sin embargo, para que el Pokemón sea introducido en la Pokéball generalmente hay que entablar un combate con él para cansarlo o debilitarlo lo suficiente como para que sea capturado. Una vez capturado, el Pokémon puede salir o ser devuelto a su Pokéball a voluntad den entrenador, pero si el Pokémon es muy testarudo y poco obediente podría escaparse por sí mismo o negarse a entrar.</p>
                <p>El vínculo entre humanos y Pokémon solo puede entenderse como de mutuo acuerdo y en la que ambos sacan beneficio. Si bien en el momento de ser capturado, el Pokémon sea reacio a estar con su entrenador, con el tiempo y el trato diario entre ambos se pueden generar estrechos vínculos de amistad. A partir del comienzo de este vínculo, el Pokémon puede aumentar su mentalidad y su fuerza, sintiéndose así más a gusto consigo mismo, o con la compañía de un humano al que tenga aprecio. Un Pokémon no puede ser malvado por combatir. Combatir es poner a prueba la fuerza y sabiduría que comparte entre humano y Pokémon</p>
                <h2 id="Generaciones">4 Generaciones de los Videojuegos</h2>
                <h3 id="Primera">4.1 Primera Generación</h3>
                <p>Los videojuegos de Pokémon originalmente fueron de estilo RPG para la consola portátil Game Boy que consistía en ayudar al profesor Oak en su investigación atrapando a todos los Pokémon existentes (151), y luchar contra entrenadores de toda la región para convertirse en el mejor entrenador Pokémon de la región Kanto. Salieron dos versiones con Pokémon exclusivos de cada una, Pokémon Rojo y Pokémon Azul, para tener así que intercambiar entre ambas versiones para conseguirlos a todos. Además, se podía pelear entre amigos con dos consolas conectadas con el Cable Link. Con el éxito de estos primeros videojuegos salió una nueva versión, Pokémon Amarillo, un poco más cercana a la serie animada de televisión. Estos juegos entrarían en lo que se conoce como primera generación.</p>
                <p>Más adelante empezaron a salir algunos otros videojuegos de temática Pokémon pero con distinto enfoque, como los Pokémon Stadium para la consola de sobremesa Nintendo 64 que se centraba en las batallas Pokémon de entrenadores. También salieron juegos de Pinball como Pokémon Pinball o de Puzzles como Pokémon Puzzle Challenge. También uno de fotografiar Pokémon, Pokémon Snap. También salió un juego llamado Hey You, Pikachu! en donde interactúas y le hablas a un Pikachu.</p>
                <p>Fuera de las videoconsolas salió un juego de cartas intercambiables, Pokémon Trading Card Game, que también salió como videojuego para la consola portátil Game Boy Color.</p>
                <h3 id="Segunda">4.2 Segunda Generación</h3>
                <p>Con el éxito de ventas, aparecieron juegos de lo que se conoce como segunda generación, Pokémon Oro, Pokémon Plata y Pokémon Cristal para la nueva consola Game Boy Color en los que se agregaron 100 nuevas especies Pokémon a las 151 existentes. Los videojuegos se desarrollaron en una nueva región, Johto, en la que se podía visitar la región Kanto habiendo compatibilidad con los videojuegos anteriores. El mismo objetivo pero una historia diferente, con nuevos protagonistas y personajes.
                Además también se lanzaron muchas secuelas de los juegos derivados de Pokémon, como Pokémon Stadium 2 y Pokémon Card GB2: GR-dan Sanjō! (este último sólo en Japón).</p>
                <h3 id="Tercera">4.3 Tercera Generacion</h3>
                <p>En la tercera generación se dio el salto a la consola Game Boy Advance. Con las ediciones Pokémon Rubí y Pokémon Zafiro y posteriormente con Pokémon Esmeralda y con una nueva tecnología que permitía mejores gráficos, y una nueva sensación al jugar. Sin embargo, se perdió completamente la compatibilidad con versiones anteriores, por lo que los videojuegos de primera y segunda generación quedaron aislados para siempre. Se agregaron 135 nuevas especies resultando en una suma de 386 Pokémon que capturar y una nueva región por explorar, Hoenn.</p>
                <p>Sin embargo, la gran mayoría de especies que aparecieron en generaciones anteriores no aparecían en estos juegos, hasta que salió una reedición de los primeros juegos, Pokémon Rojo Fuego y Pokémon Verde Hoja que añadió la posibilidad de conseguirlos.</p>
                <p>En esta época aparecieron también otros juegos de géneros distintos: Pokémon Dash, un juego de carreras; Pokémon Link!, un juego de puzzle; Pokémon Colosseum, un juego de batallas; Pokémon XD: Tempestad Oscura, un juego en el que puedes luchar contra Pokémon oscuros, como el Lugia oscuro; Pokémon Mundo misterioso: Equipo de rescate rojo y Equipo de rescate azul, en los que el protagonista se convierte en un Pokémon y debe explorar mazmorras; y Pokémon Ranger, en el que el protagonista es un guardabosques y se captura a los Pokémon trazando círculos con el lápiz táctil del Nintendo DS.</p>
                <h3 id="Cuarta">4.4 Cuarta Generacion</h3>
                <p>En el año 2006 llegó la cuarta generación, donde los videojuegos Pokémon Diamante y Pokémon Perla, y posteriormente Pokémon Platino son para Nintendo DS, con el mismo objetivo pero con 107 nuevas criaturas, dando un total de 493 Pokémon existentes y la nueva región, Sinnoh.También forman parte de esta generación Pokémon Battle Revolution para Wii, parecido a Pokémon Colosseum pero compatible con los anteriores; PokéPark un juego para Wii en el que únicamente podrás manejar a Pikachu; Pokémon Mundo misterioso: Exploradores del tiempo y Exploradores de la oscuridad y Pokémon Mundo misterioso: Exploradores del cielo en el que viajarás por nuevas mazmorras; Pokémon Ranger: Sombras de Almia en el que podrás capturar nuevos Pokémon y viajarás por la nueva región de Almia y también Pokémon Ranger: Trazos de Luz en el que viajarás por la región de Oblivia y podrás capturar más Pokémon que no habían aparecido.
                Al final de esta generación, en el 2009, aparecen Pokémon Oro HeartGold y Pokémon Plata SoulSilver, reediciones de los juegos Pokémon Oro y Pokémon Plata de la segunda generación, actualizados a la época y con la posibilidad de capturar Pokémon de las regiones Hoenn y Sinnoh.</p>
                <h3 id="Quinta">4.5 Quinta Generacion</h3>
                <p>En el año 2010, se anunció la quinta generación con dos nuevos juegos: Pokémon Negro y Pokémon Blanco, que dieron lugar a la nueva región Teselia, en la cual se introdujeron 156 nuevos Pokémon, con los que se llegó a un total de 649 especies diferentes. El objetivo de estos juegos no es otro más que atraparlos a todos y ser el mejor.
                Poco después de la salida de Pokémon Negro y Pokémon Blanco, se anuncia Aprende con Pokémon: Aventura entre las teclas, un juego de la quinta generación orientado a un público infantil; y también Pokémon Card Game: How to Play DS, un juego parecido al Pokémon Trading Card Game pero educativo; más tarde salió Pokémon Conquest, un juego ambientado en el Japón feudal (que no llegó a Europa); también se anunció en septiembre la nueva edición de Pokémon Mundo misterioso: Portales al infinito, que fue para Nintendo 3DS. También han salido aplicaciones para la Nintendo 3DS como la Pokédex 3D, el RAdar Pokémon, y la Pokédex 3D Pro, una versión nueva en la que salen las nuevas formas y todos los Pokémon de otras regiones. Además, se estrena la decimocuarta película de Pokémon en los cines japoneses en junio y julio del 2011, que además es dual: son 2 películas con el mismo argumento en la que en una el protagonista es Reshiram y en la otra es Zekrom.
                A finales de febrero de 2012, en el programa de Pokémon Smash se anunciaron dos nuevos juegos de la quinta generación: Pokémon Negro 2 y Pokémon Blanco 2, los cuales se desarrollan también en la región Teselia, pero dos años después en el tiempo de Pokémon Negro y Pokémon Blanco, con cambios en la historia, personajes y lugares. También se pueden encontrar Pokémon de otras regiones antes de pasar la Liga Pokémon. No se introducen nuevos Pokémon, pero sí nuevas formas de los Pokémon legendarios del trío de las fuerzas de la naturaleza, Kyurem y Keldeo.</p>
                <h3 id="Sexta">4.6 Sexta Generacion</h3>
                <p>Fue anunciada oficialmente durante el Pokémon Direct, en simultáneo en todo el mundo y en diferentes idiomas, el día 8 de enero de 2013 por el mismísimo Satoru Iwata, presidente de Nintendo. Días atrás, se reveló al final de un comercial de Pokémon Negro 2 y Pokémon Blanco 2 que el 8 de enero, en el evento Pokémon Direct, se haría un anuncio importante que revolucionaría la franquicia.
                Esta generación debuta con los videojuegos en 3D Pokémon X y Pokémon Y y Pokémon Rubí Omega y Pokémon Zafiro Alfa para Nintendo 3DS. Unas de sus novedades son los gráficos en 3D totalmente renovados y diferentes a cualquier juego anterior de la franquicia. Se añaden los patines como nueva forma de desplazamiento, las megaevoluciones, la región de Kalos y se introdujeron 72 nuevos Pokémon sumando un total de 721 de especies diferentes, siendo así la generación en la que menos Pokémon se han introducido hasta el momento. Otra gran novedad es el la introducción de un nuevo tipo, el tipo hada.</p>
                <h3 id="Septima">4.7 Septima Generacion</h3>
                <p>Fue anunciada oficialmente durante el Pokémon Direct del 26 de febrero del 2016, cuando se anunciaron los juegos para el 3DS Pokémon Sol y Pokémon Luna. Esta generación implementa características nuevas como los movimientos Z, el recorrido insular, las formas regionales, entre otras. Además, introduce 88 nuevos Pokémon provenientes de la región Alola, aumentando el total a 809 especies descubiertas.
                Al año siguiente, el día 17 de noviembre del 2017, salen a la venta los juegos Pokémon Ultrasol y Pokémon Ultraluna, trayendo con ellos como novedad 4 nuevos ultraentes y un Pokémon singular, la posibilidad de que los jugadores visiten el Ultraespacio y combatan a antiguos antagonistas presentes en el Team Rainbow Rocket tales como Giovanni, Magno, Aquiles, Helio, Ghechis, Lysson y Fabio. Además de nuevas formas en Pokémon como Lycanroc, Pikachu y Necrozma.
                Posteriormente a finales del 2018 sale a la venta los primeros videojuegos Pokémon principales para Nintendo Switch: Pokémon: Let's Go, Pikachu! y Pokémon: Let's Go, Eevee!, basándose a su vez en el videojuego de la primera generación Pokémon Amarillo. Trayendo consigo también a los Pokémon singulares: Meltan y su evolución Melmetal.</p>
                <h3 id="Octava">4.8 Octava Generacion</h3>
                <p>Fue anunciada oficialmente durante el Pokémon Direct del 27 de febrero del 2019, cuando se anunciaron los juegos para la consola híbrida Nintendo Switch: Pokémon Espada y Pokémon Escudo, los cuales salieron a la venta el 15 de noviembre del 2019 y su historia se desarrolla en la región de Galar. Además, se introdujeron 89 nuevos Pokémon, aumentando el total de especies a 898. En estos juegos se implementan características como los fenómenos Dinamax, Gigamax, entre otros. Así como la introducción de nuevas formas regionales.</p>
                <h3 id="Novena">4.9 Novena Generacion</h3>
                <p>Fue anunciada oficialmente durante el Pokémon Presents del 27 de febrero de 2022, cuando se anunciaron los juegos para la consola Nintendo Switch: Pokémon Escarlata y Pokémon Púrpura, los cuales salieron a la venta el viernes 18 de noviembre de 2022 y su historia se desarrolla en la región de Paldea, inspirada en la Península Ibérica. Hasta ahora se han introducido 110 Pokémon, haciendo un total de 1008 especies diferentes, incluyendo formas regionales. Además, se introduce el fenómeno de la teracristalización.</p>
                <h2 id="Merchadising">5 Merchandising</h2>
                <h3 id="Anime">5.1 Anime</h3>
                <p>El anime relata las aventuras de Ash Ketchum, un entrenador Pokémon que junto con su Pokémon inicial Pikachu, obtenido de manos del profesor Oak en Pueblo Paleta, recorre las regiones con el objetivo de reunir las medallas de gimnasio necesarias para participar en una Liga Pokémon y ganarla, y así estar un paso más cerca de convertirse en un maestro Pokémon. Actualmente viaja de región en región junto a Goh, obteniendo información para el Laboratorio Cerise/Cerezo. Además, Ash combate contra los entrenadores que se encuentra para así ascender hasta la Liga Master de la Serie Mundial de Coronación y así vencer al campeón, Leon/Lionel.
                Existen actualmente siete series, o sagas, del anime:</p>
                <ul>
                    <li><b>El Comienzo: </b>Engloba el viaje de Ash reuniendo medallas por Kanto y el Archipiélago Naranja. En su viaje le ahan acompañado Misty, Brook y Tracey.</li>
                    <li><b>Oro y Plata: </b>Engloba el viaje de Ash reuniendo medallas por Johto. En su viaje le han acompañado Misty y Brock.</li>
                    <li><b>Rubí y Zafiro: </b>Engloba el viaje de Ash reuniendo medallas por Hoenn y reuniendo símbolos por Kanto. En su viaje le han acompañado May/Aura, Max y Brock.</li>
                    <li><b>Diamente y Perla: </b>Engloba el viaje de Ash reuniendo medallas por Sinnoh únicamente. En su viaje le han acompañado Dawn/Maya, Brock, Lyra/Lira y Khoury</li>
                    <li><b>Negro y Blanco: </b>Engloba el viaje de Ash reuniendo medallas por Unova/Teselia y explorando las Islas Decolora/Decoloras. En su viaje le han acompañado Iris, Cilan/Millo, N y Alexa/Alexia.</li>
                    <li><b>XY: </b>Engloba el viaje que Ash está haciendo para reunir las medallas por Kalos. En su viaje le acompañan Serena, Clemont/Lem y Bonnie/Clem y le ha acompañado Korrina/Corelia.</li>
                    <li><b>Sol y Luna: </b>Muestra la nueva aventura que Ash comenzó en Melemele en la región de Alola, donde empieza a asistir a la Escuela Pokémon.</li>
                    <li><b>Viajes Pokemon: </b>Muestra la nueva aventura de Ash comenzó su aventura en Ciudad Carmín y recorre todo el mundo Pokémon acompañado por Goh.</li>
                    <li><b>Horizontes Pokémon: </b>que muestra la nueva aventura de Liko y Rod en la región de Paldea.</li>
                </ul>
                <h3 id="Películas">5.2 Peliculas</h3>
                <p>En las películas de Pokémon, aparte del Equipo/Team Rocket también hay personajes invitados que junto con Ash y sus amigos se involucran con uno o varios de los Pokémon legendarios e incluso con nuevos Pokémon que recién hacen su aparición en los videojuegos. Muchas de estas películas han tenido éxito en la industria del cine a partir del gran impacto que tuvo la primera película.
                Las primeras seis películas iban acompañadas de un corto con las aventuras de Pikachu, en las películas posteriores se dejaron a un lado, para darle más tiempo a la trama principal. Aun así a partir de la película 15 se volvió a esa costumbre. Sin embargo, la película 20, que celebró el vigésimo aniversario del anime y sus películas, no incluyó ningún cortometraje.</p>
                <h3 id="Manga">5.3 Manga</h3>
                <p>Hay varios mangas de Pokémon. Los mangas se suelen sacar en Japón por Shogakukan, y traducido al inglés en Norteamérica principalmente por VIZ Media, Chuang Yi en los países asiáticos, Editorial Norma en Europa y Editorial Panini en México. Se basan en el anime y otros en los videojuegos, siendo este último más conocido.</p>
                <h3 id="Cartas">5.4 Juego de Cartas</h3>
                <p>El Juego de Cartas Coleccionables Pokémon (JCC Pokémon o Pokémon TCG) es un juego desarrollado por Pokémon y Nintendo. Fue lanzado al mercado el 20 de octubre de 1996 en Japón y publicado por Media Factory. Consiste en cartas coleccionables con las que se pueden jugar. Hay cartas de Pokémon, cartas de energía, cartas de entrenador que pueden ser de Partidario, Estadio, Objeto, Herramienta Pokémon, y antiguamente Máquina Técnica (MT).</p>
            </div>
        </div>);
}

export default Contenido;